# Generated by Django 4.1.2 on 2022-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.AddField(
            model_name='file',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
