# Generated by Django 4.1.2 on 2022-10-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_video_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_bw',
        ),
        migrations.RemoveField(
            model_name='video',
            name='time',
        ),
        migrations.RemoveField(
            model_name='video',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='video',
            name='newtext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
