# Generated by Django 4.1.2 on 2022-10-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_remove_video_file_remove_video_file_bw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='newtext',
            field=models.TextField(null=True),
        ),
    ]
