# Generated by Django 4.1.2 on 2022-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_alter_video_newtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='video',
            name='file_bw',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
