# Generated by Django 4.1.2 on 2022-10-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0006_video_file_video_file_bw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(null=True, upload_to='mainImage'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_bw',
            field=models.FileField(null=True, upload_to='bwImage'),
        ),
    ]
