# Generated by Django 4.1.2 on 2022-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_alter_video_file_alter_video_file_bw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_bw',
            field=models.FileField(null=True, upload_to='NEWbwImage'),
        ),
    ]
